---
name: CI
on:
  pull_request:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4

  tests:
    name: tests
    needs: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Test code
        run: go test -race -v ./...
